shell /usr/bin/zsh

include colors.conf

font_family                   CaskaydiaCove Nerd Font
font_size                     13
bold_font                     auto
italic_font                   auto
bold_italic_font              auto
disable_ligatures             never

cursor_trail                  10
cursor_shape                  block
cursor_stop_blinking_after    4.0
cursor_trail_decay            0.15 0.4
cursor_trail_start_threshold  3

enable_audio_bell             no

background_opacity            0.6
window_padding_width          10
hide_window_decorations       yes

# -------------------------------------------------------------------
# Nerd Fonts v3.x glyph fallback

# Seti-UI + custom icons
symbol_map U+E5FA-U+E6B1 Symbols Nerd Font Mono
symbol_map U+E600-U+E6C5 Symbols Nerd Font Mono

# Devicons Range
symbol_map U+E700-U+E7C5 Symbols Nerd Font Mono

# Font Awesome / Material Design / Codicons
symbol_map U+F000-U+F2E0 Symbols Nerd Font Mono
symbol_map U+F300-U+F372 Symbols Nerd Font Mono
symbol_map U+F400-U+F532 Symbols Nerd Font Mono
symbol_map U+F0001-U+F1AF0 Symbols Nerd Font Mono
