selection_background    {{base16.base02.default.hex}}

# 16 terminal colors:
# black
color0 {{colors.surface_container_highest.default.hex}}
color8 {{colors.surface_container_highest.default.hex}}

# red
color1 {{palettes.error._60.hex}}
color9 {{palettes.error._60.hex}}

# green
color2  #94e68c
color10 #94e68c

# yellow
color3  #eed7a6
color11 #eed7a6

# blue
color4  {{palettes.primary._70.hex}}
color12 {{palettes.primary._70.hex}}

# magenta
color5  {{palettes.primary._80.hex}}
color13 {{palettes.primary._80.hex}}

# cyan
color6  {{palettes.secondary._80.hex}}
color14 {{palettes.secondary._80.hex}}

# white
color7  {{palettes.neutral_variant._95.hex}}
color15 {{palettes.secondary._80.hex}}
